; Show intro page
; Intro page Color and Font Info
; Bitmaps and links info
; Cursor bitmap Info
; Introduction page current mode
; (Artist mode : 0 , Greeting mode=1)
; Greeting mode text data info
; Artist mode text data info

[Introduction]
Version=0
OnOff=1
Mode=0
Time=7000
BkgColor=200,200,200
TextColor=0,0,0
TextColorHot=0,0,255
TextFontInfo=1.000000,0.100000,-11,0,0,0,244,0,0,0,0,3,2,1,34,Arial
Cover=cover.jpg
CoverLoc=0,0,256,256
Logo=cover.jpg
LogoLoc=467,3,40,40
Banner=banner.jpg
BannerLoc=256,195,256,64
AlbumLink=
LogoLink=
BannerLink=
CursorLink=hotspot.jpg
CursorNormal=arrow.jpg
Title=
TitleLoc=260,35,248,14
To=
ToLoc=260,55,248,14
Message=LAVA! defines the next dimension in Internet music entertainment : Interactive 3D MusicVideo.   LAVA! is a suite of applications which enable the playback, production and merchandising of Internet music enhanced by realtime 3D visualisations.
MessageLoc=260,75,248,79
From=
FromLoc=260,160,248,14
Date=
DateLoc=260,180,248,14
GenreID=124
Genre=Trip-Hop
GenreLoc=260,35,200,14
Song=Song Title: Polyesterday
SongLoc=260,55,248,14
Artist=Artist: Gus Gus
ArtistLoc=260,75,248,14
Album=Album: Shaken Not Stirred
AlbumLoc=260,95,248,14
Link=www.epitonic.com
LinkLoc=260,115,248,14
Email=love@epitonic.com
EmailLoc=260,135,248,14
Comments=(Thievery Corporation Remix)
CommentsLoc=260,155,248,25
YearCopyRight=(c) Copyright 2000
YearCopyRightLoc=260,180,248,14

